apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  SPRING_RABBITMQ_HOST: "rabbitmq"
  SPRING_RABBITMQ_PORT: "5672"
  S3_REGION: "eu-west-3"
  S3_PATH_STYLE_ACCESS: "false"
  APP_FRONTEND_URL: "https://staging.legalcase.ng-itconsulting.com"
  MANAGEMENT_HEALTH_RABBIT_ENABLED: "false"
  MANAGEMENT_HEALTH_MAIL_ENABLED: "false"
  APP_STRIPE_ENABLED: "true"
  APP_MAIL_ENABLED: "true"
