// Auto-généré depuis TOOL_REGISTRY (decisional-tools-panel.component.ts)
// + seeds decision_tool_visibility_rules (legal_domain/country).
// NE PAS ÉDITER À LA MAIN — régénérer via :
//   node scripts/build-landing-catalog.mjs
// (SF-158-04 F-158 V4 — remplace l'ancien build-catalog.py).
//
// 254 outils. Répartition :
//   TRAVAIL: FR=73 BE=55
//   IMMIGRATION: FR=43 BE=15
//   FAMILLE: FR=53 BE=15
//
// 2 id(s) sans règle de visibilité — domain/country dérivés par défaut (préfixe id / label) :
//   clause-non-concurrence-be -> TRAVAIL/BE
//   F-136-travail-procedure -> TRAVAIL/FR

export type LandingToolDomain = 'TRAVAIL' | 'IMMIGRATION' | 'FAMILLE';
export type LandingToolCountry = 'FR' | 'BE';
export type LandingToolType = 'CALCULATEUR' | 'SCORING' | 'COMPARATEUR' | 'GÉNÉRATEUR' | 'DÉTECTEUR' | 'OUTIL';

export interface LandingTool {
  id: string;
  label: string;
  domain: LandingToolDomain;
  country: LandingToolCountry;
  type: LandingToolType;
}

export const LANDING_TOOLS_CATALOG: LandingTool[] = [
  { id: 'F-FA-11-desunion-irremediable-be', label: 'Désunion irrémédiable (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'autorite-parentale-be', label: 'Autorité parentale (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'contestation-filiation-be', label: 'Contestation de filiation (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'contribution-alimentaire-enfants-be', label: 'Contribution alimentaire des enfants (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'contribution-conjoint-be', label: 'Pension alimentaire entre ex-époux (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'divorce-dc-be', label: 'Divorce par consentement mutuel (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'divorce-ddi-3voies-be', label: 'Divorce — Désunion irrémédiable 3 voies (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'liquidation-partage-be', label: 'Liquidation-partage post-divorce (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'mariage-etranger-be-reconnaissance', label: 'Reconnaissance mariage / divorce étranger (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'cohabitation-legale-be', label: 'Cohabitation légale — régime (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'adoption-be', label: 'Adoption — recevabilité (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'kafala-be-recueil-legal', label: 'Recueil légal (kafala) — Belgique', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'gpa-be-situation-contentieuse', label: 'Filiation post-GPA — Belgique', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'regime-algerien-be', label: 'Régime algérien — mariage / talaq / dot (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'regime-be-separation-biens', label: 'Régime de séparation de biens (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'dip-be-loi-applicable-famille', label: 'Loi applicable en droit de la famille (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'dip-be-reconnaissance-decision-etrangere', label: 'Reconnaissance / exequatur d\'une décision familiale étrangère (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'pacte-successoral-be-2018', label: 'Pacte successoral 2018 (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'protection-majeur-be', label: 'Protection du majeur (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'regime-mat-be-communaute-legale', label: 'Régime de communauté légale (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'succession-be-acceptation-renonciation', label: 'Acceptation / renonciation à succession (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'succession-be-devolution-reserve', label: 'Dévolution et réserve héréditaire (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'tribunal-famille-be-mesures-prov', label: 'Mesures provisoires Tribunal de la famille (Belgique)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
  { id: 'F-152-divorce-consentement-scoring', label: 'Divorce par consentement mutuel — scoring (FR/BE)', domain: 'FAMILLE', country: 'FR', type: 'SCORING' },
  { id: 'F-153-fourchettes-jaf', label: 'Fourchettes JAF (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-01-prestation-compensatoire', label: 'Prestation compensatoire (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-02-pension-alimentaire', label: 'Pension alimentaire enfant (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-04-liquidation-communaute', label: 'Liquidation de communauté (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-05-partage-immobilier', label: 'Partage immobilier', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-06-calendrier-garde', label: 'Calendrier de garde', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-07-checklist-divorce', label: 'Checklist divorce', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-08-divorce-alteration', label: 'Divorce — altération du lien (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-09-divorce-faute', label: 'Divorce pour faute (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-10-divorce-accepte', label: 'Divorce accepté (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-12-mesures-provisoires', label: 'Mesures provisoires (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-13-revisions-post-divorce', label: 'Révisions post-divorce (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-14-ordonnance-protection', label: 'Ordonnance de protection (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-15-recompenses', label: 'Récompenses entre époux (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-16-communaute-universelle', label: 'Communauté universelle (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-17-partage-judiciaire', label: 'Partage judiciaire (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-adoption', label: 'Adoption (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-contestation-paternite', label: 'Contestation de paternité (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-possession-etat', label: 'Possession d\'état (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-recherche-paternite', label: 'Recherche de paternité (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-reconnaissance-paternelle', label: 'Reconnaissance paternelle (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-autorite-parentale', label: 'Autorité parentale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-changement-residence', label: 'Changement de résidence de l\'enfant (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-desaccords-parentaux', label: 'Désaccords parentaux (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-20-pacs-dissolution', label: 'Dissolution de PACS (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-21-separation-corps', label: 'Séparation de corps (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-22-indivision', label: 'Indivision (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-23-ordonnance-requete', label: 'Ordonnance sur requête', domain: 'FAMILLE', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-FA-24-devolution-legale', label: 'Dévolution légale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-donation', label: 'Donation (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-indivision-successorale', label: 'Indivision successorale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-partage-successoral', label: 'Partage successoral (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-rapport-succession', label: 'Rapport à succession (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-reserve-heriditaire', label: 'Réserve héréditaire (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-testament-validite', label: 'Testament — validité (FR)', domain: 'FAMILLE', country: 'FR', type: 'SCORING' },
  { id: 'F-FA-25-majeurs-proteges', label: 'Majeurs protégés (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-26-changement-etat-civil', label: 'Changement d\'état civil (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-27-pma-gpa', label: 'PMA / GPA — bioéthique (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-ADOPTION-INTERNATIONALE', label: 'Adoption internationale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-ADOPTION-INTRA', label: 'Adoption intra-familiale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-ARIPA-RECOUVREMENT', label: 'ARIPA recouvrement (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-AUDITION-MINEUR', label: 'Audition du mineur (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-DONATION-ENTRE-EPOUX', label: 'Donation entre époux (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-DONATION-PARTAGE', label: 'Donation-partage (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-INDIGNITE-SUCCESSORALE', label: 'Indignité successorale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-PARTAGE-NOTARIAL', label: 'Partage successoral notarié (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-PRESOMPTION-PATERNITE', label: 'Présomption de paternité (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-RECEL-SUCCESSION', label: 'Recel de succession (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-RETRAIT-AP', label: 'Retrait autorité parentale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-XX-delegation-ap', label: 'Délégation autorité parentale (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'acceptation-renonciation-succession', label: 'Acceptation / renonciation à succession', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'mediation-familiale-pre-saisine', label: 'Médiation familiale pré-saisine', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-annexe13-be', label: 'Annexe 13 — OQT (Belgique)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-40bis-cohabitant-ue-be', label: 'Article 40bis — cohabitant UE (Belgique)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-40ter-familial-belge-be', label: 'Article 40ter — regroupement familial belge (Belgique)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-9bis-humanitaire-be', label: 'Article 9bis — humanitaire (Belgique)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-9ter-medical-be', label: 'Article 9ter — médical (Belgique)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-25-single-permit-be', label: 'Permis unique BE (travail+séjour)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-26-regroupement-10ter-be', label: 'Regroupement familial 10ter (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-27-regroupement-10bis-be', label: 'Regroupement familial 10bis (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-28-naturalisation-12bis-be', label: 'Naturalisation 12bis (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-29-naturalisation-conjoint-belge-be', label: 'Naturalisation conjoint Belge (art. 16)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-30-aesm-mena-be', label: 'AESM + tutelle DGDE (MENA)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-31-cce-annulation-30j-be', label: 'Recours CCE annulation 30j (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-32-cce-extreme-urgence-5j-be', label: 'Recours CCE extrême urgence 5j (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-33-annexe13quinquies-ie-be', label: 'Annexe 13quinquies OQT + interdiction entrée (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-34-protection-temporaire-ukraine-be', label: 'Protection temporaire Ukraine (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-53-carte-a-prorogation-be', label: 'Prorogation carte A (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-54-carte-b-sejour-illimite-be', label: 'Carte B séjour illimité (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-55-residence-longue-duree-ue-be', label: 'Résident longue durée UE (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-56-detention-centre-ferme-be', label: 'Détention centre fermé (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-57-cce-suspension-be', label: 'Recours CCE suspension (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-58-victime-traite-be', label: 'Victime de la traite (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-01-checklist-pieces', label: 'Checklist pièces immigration', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-05-arbre-decisionnel-titre', label: 'Arbre décisionnel titre de séjour (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-06-recours', label: 'Recours immigration (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-07-droit-au-travail', label: 'Droit au travail des étrangers (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-oqtf-avec-delai-fr', label: 'OQTF avec délai (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-oqtf-sans-delai-fr', label: 'OQTF sans délai (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-referes-admin-fr', label: 'Référés administratifs OQTF (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-etudiant', label: 'AES étudiant (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-famille', label: 'AES familial (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-humanitaire', label: 'AES humanitaire (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-metiers-tension', label: 'AES métiers en tension (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-11-changement-statut', label: 'Changement de statut (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-12-asile-avance', label: 'Asile avancé (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-13-naturalisation', label: 'Naturalisation (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-17-regime-algerien', label: 'Régime algérien (accord franco-algérien)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-19-mineurs', label: 'Mineurs immigration (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-20-mesures-eloignement', label: 'Mesures d\'éloignement (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-21-jld-retention-fr', label: 'JLD rétention administrative (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-22-dublin-recours-fr', label: 'Dublin — recours (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-23-crrv-refus-visa-fr', label: 'CRRV — refus de visa (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-24-victime-violences-l4256-fr', label: 'Victime de violences — L.425-6 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-25-etranger-malade-l4259-fr', label: 'Étranger malade — L.425-9 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-26-regroupement-familial-fr', label: 'Regroupement familial (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-27-vpf-liens-personnels-l42323-fr', label: 'VPF liens personnels L.423-23 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-28-vls-ts-validation-ofii-fr', label: 'Validation VLS-TS OFII (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-29-oqtf-categories-l6111-fr', label: 'OQTF catégories L.611-1 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-30-aes-presence-prouvee-fr', label: 'AES présence prouvée (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-31-renouvellement-delai-depot-fr', label: 'Renouvellement délai dépôt (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-32-recepisse-attestation-fr', label: 'Récépissé vs attestation (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-33-ofpra-introduction-fr', label: 'OFPRA introduction (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-34-aj-cnda-fr', label: 'AJ CNDA (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-35-victime-traite-l4251-fr', label: 'Victime traite L.425-1 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-36-carte-resident-l4261-fr', label: 'Carte de résident L.426-1 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-37-anef-procedure-fr', label: 'ANEF procédure / pannes (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-38-mna-evaluation-age-fr', label: 'MNA évaluation âge (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-39-naturalisation-recours-tj-fr', label: 'Recours TJ naturalisation (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-40-naturalisation-recours-ta-fr', label: 'Recours TA Nantes naturalisation (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-41-appel-caa-cassation-ce-fr', label: 'Appel CAA / cassation CE (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-42-assignation-residence-fr', label: 'Assignation à résidence (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-43-itf-judiciaire-fr', label: 'ITF judiciaire (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-44-ue-eee-suisse-sejour-fr', label: 'Séjour UE/EEE/Suisse (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-45-retrait-titre-fraude-fr', label: 'Retrait titre pour fraude (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-46-autorisation-travail-employeur-fr', label: 'Autorisation travail employeur (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-132-rupture-amiable-info', label: 'Rupture amiable — informations', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-06-requete-tribunal-travail', label: 'Requête tribunal du travail (BE)', domain: 'TRAVAIL', country: 'BE', type: 'GÉNÉRATEUR' },
  { id: 'F-DT-27-motif-grave-be', label: 'Motif grave (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-28-avantages-conventionnels-be', label: 'Avantages conventionnels (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-29-credit-temps-be', label: 'Crédit-temps (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'at-fedris-declaration', label: 'Déclaration AT Fedris (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'at-mp-rente-capital-be', label: 'Rente AT/MP vs capitalisation (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'auditorat-travail-be', label: 'Auditorat du travail (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'bien-etre-rps-conseiller-prevention', label: 'Saisine CPAP — Conseiller en Prevention RPS (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'c4-onem-checklist', label: 'Checklist C4 ONEM (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'clause-ecolage-be', label: 'Clause d\'écolage (Belgique — art. 22bis)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'clause-non-concurrence-be', label: 'Clause de non-concurrence (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'code-penal-social-be', label: 'Code pénal social (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'conge-education-paye-region', label: 'Congé-éducation payé — régionalisé (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'conge-paternite-naissance-be', label: 'Conge paternite / naissance (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'contestation-c4-onem', label: 'Contestation C4 ONEM (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'cumul-rcc-allocations', label: 'Cumul RCC + allocations (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'delegue-syndical-cct-5', label: 'Délégué syndical — CCT n° 5 (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'discrimination-be-handicap-amenagement', label: 'Aménagements raisonnables handicap (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'droit-deconnexion-be', label: 'Droit à la déconnexion (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'eco-cheques-cheques-repas-be', label: 'Éco-chèques + chèques-repas (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'egalite-femmes-hommes-be', label: 'Égalité salariale F/H (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'elections-sociales-be', label: 'Élections sociales (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'etudiant-jobiste-be', label: 'Étudiant jobiste (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'flexi-job-be', label: 'Flexi-job (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'harcelement-be-procedure-formelle', label: 'Harcèlement procédure formelle (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'inastri-statut-travailleur-independant', label: 'INASTI — statut travailleur indépendant (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'interim-be-cct-322', label: 'Intérim (Belgique — CCT 322)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'interim-be-indemnite-fin-mission', label: 'Indemnité fin de mission intérim (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'CALCULATEUR' },
  { id: 'interruption-carriere-soins-parental', label: 'Interruption de carriere — Conge parental (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-acte-equivalent', label: 'Acte équipollent à rupture (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-cct109-deraisonnable', label: 'Score CCT 109 — licenciement déraisonnable (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'SCORING' },
  { id: 'licenciement-be-collectif-renault', label: 'Licenciement collectif — Loi Renault (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-fermeture-entreprise', label: 'Fermeture d\'entreprise (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-formule-claeys', label: 'Préavis Formule Claeys (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-protection-deleguee', label: 'Licenciement — protection délégué (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-protection-grossesse', label: 'Protection grossesse (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'licenciement-be-statut-unique-preavis', label: 'Préavis statut unique (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'mp-fedris-reconnaissance', label: 'MP Fedris reconnaissance (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'outplacement-be-general-30sem', label: 'Outplacement BE général (préavis ≥ 30 sem.)', domain: 'TRAVAIL', country: 'BE', type: 'GÉNÉRATEUR' },
  { id: 'outplacement-be-obligatoire-45', label: 'Outplacement obligatoire 45+ (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'pecule-vacances-be', label: 'Pécule de vacances (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'prescription-be-litige-travail', label: 'Prescription — litige travail (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'rappel-salaire-be', label: 'Rappel de salaire (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'CALCULATEUR' },
  { id: 'rcc-be-conditions', label: 'RCC BE — conditions d\'éligibilité', domain: 'TRAVAIL', country: 'BE', type: 'SCORING' },
  { id: 'rcc-be-entreprise-difficulte', label: 'RCC BE — entreprise en difficulté', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'rcc-be-indemnite-complementaire', label: 'RCC BE — indemnité complémentaire', domain: 'TRAVAIL', country: 'BE', type: 'CALCULATEUR' },
  { id: 'rcc-be-longue-carriere', label: 'RCC BE — longue carrière', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'rcc-be-metiers-lourds', label: 'RCC métiers lourds (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'refere-tribunal-travail-be', label: 'Référé tribunal du travail (BE)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'semaine-4-jours-be', label: 'Semaine de 4 jours (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'teletravail-be-cct-85-149', label: 'Télétravail (Belgique — CCT 85 / 149)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'transaction-be-travail', label: 'Transaction fin de contrat (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'transfert-entreprise-cct-32bis', label: 'Transfert d\'entreprise CCT 32bis (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'travail-noir-be-dimona', label: 'Travail noir DIMONA (Belgique)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-132-rupture-conv-indemnite', label: 'Rupture conventionnelle — indemnité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-136-travail-procedure', label: 'Procédure prud\'homale (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-03-prescription-litige', label: 'Prescription du litige (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-04-fiche-prudhomale', label: 'Fiche prud\'homale (FR)', domain: 'TRAVAIL', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-DT-07-anciennete-conges-prime', label: 'Ancienneté, congés et primes (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-08-licenciement-validity', label: 'Licenciement — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-09-comparateur-indemnites', label: 'Comparateur d\'indemnités (FR)', domain: 'TRAVAIL', country: 'FR', type: 'COMPARATEUR' },
  { id: 'F-DT-10-rupture-conv-validity', label: 'Rupture conventionnelle — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-100-reglement-interieur-validite', label: 'Règlement intérieur — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-104-vrp-indemnite-clientele', label: 'VRP : préavis et indemnité de clientèle (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-105-journaliste-statut', label: 'Statut journaliste (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-106-intermittent-spectacle-are', label: 'Intermittent spectacle ARE (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-107-cadre-dirigeant-statut', label: 'Statut cadre dirigeant (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-108-particulier-employeur-cesu', label: 'Particulier employeur / CESU (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-109-stagiaire-gratification-requalification', label: 'Stagiaire gratification (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-11-harcelement-licenciement-nul', label: 'Harcèlement → licenciement nul (FR)', domain: 'TRAVAIL', country: 'FR', type: 'DÉTECTEUR' },
  { id: 'F-DT-110-apprentissage-rupture', label: 'Rupture apprentissage (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-12-discrimination-dommages-interets', label: 'Discrimination — dommages-intérêts (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-13-licenciement-economique', label: 'Licenciement économique (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-14-pse-validite', label: 'PSE — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-15-inaptitude', label: 'Inaptitude — indemnités (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-16-licenciement-nul-detection', label: 'Détection de licenciement nul (FR)', domain: 'TRAVAIL', country: 'FR', type: 'DÉTECTEUR' },
  { id: 'F-DT-17-indemnite-precarite-cdd', label: 'Indemnité de précarité CDD (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-18-fin-mission-interim', label: 'Fin de mission intérim (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-19-heures-sup', label: 'Heures supplémentaires (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-20-rappel-salaire', label: 'Rappel de salaire (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-21-travail-dissimule', label: 'Travail dissimulé (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-22-requalification-cdd-cdi', label: 'Requalification CDD en CDI (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-23-requalification-interim-cdi', label: 'Requalification intérim en CDI (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-24-non-concurrence', label: 'Clause de non-concurrence (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-25-indemnite-preavis', label: 'Indemnité de préavis (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-26-conges-payes-indemnite', label: 'Indemnité congés payés (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-30-protection-rp', label: 'Protection représentant du personnel (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-31-transaction', label: 'Transaction (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-32-documents-fin-contrat', label: 'Documents de fin de contrat (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-33-at-mp', label: 'AT/MP — accident et maladie pro (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-34-refere-prudhomal', label: 'Référé prud\'homal (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-35-contestation-are-fr', label: 'Contestation ARE Pôle emploi (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-36-licenciement-faute-grave-lourde', label: 'Faute grave / faute lourde (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-36-procedure-nullite-licenciement', label: 'Nullité de procédure de licenciement (FR)', domain: 'TRAVAIL', country: 'FR', type: 'DÉTECTEUR' },
  { id: 'F-DT-37-licenciement-cdi-chantier', label: 'Licenciement CDI de chantier (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-38-rupture-periode-essai', label: 'Rupture de période d\'essai (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-39-prise-acte-rupture', label: 'Prise d\'acte de la rupture (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-40-resiliation-judiciaire-cph', label: 'Résiliation judiciaire du contrat (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-41-demission-validite-equivoque', label: 'Démission — validité et caractère équivoque (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-42-abandon-poste-presomption-demission', label: 'Abandon de poste / présomption de démission (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-43-rupture-anticipee-cdd', label: 'Rupture anticipée du CDD (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-44-csp-crp-conformite', label: 'CSP/CRP — conformité de la proposition (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-46-pdv-rcc-conformite', label: 'PDV / RCC — conformité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-48-mise-a-pied-disciplinaire', label: 'Mise à pied disciplinaire — régularité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-49-temps-partiel-requalification', label: 'Temps partiel — requalification (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-50-forfait-jours-validite', label: 'Forfait jours — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-56-egalite-salariale-femmes-hommes', label: 'Égalité salariale femmes/hommes (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-59-harcelement-procedure-interne', label: 'Harcèlement procédure interne (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-61-lanceur-alerte-protection', label: 'Protection du lanceur d’alerte (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-64-burnout-reconnaissance-mp', label: 'Burn-out — reconnaissance MP (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-65-elections-cse-conformite', label: 'Élections CSE — conformité procédure (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-66-nao-negociation-annuelle', label: 'NAO négociation annuelle (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-67-accord-entreprise-validite', label: 'Accord d\'entreprise — validité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-69-delegation-syndicale-protection', label: 'Délégué syndical / RSS (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-70-modification-contrat-refus', label: 'Modification du contrat — refus du salarié (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-71-mutation-clause-mobilite', label: 'Mutation — validité de la clause de mobilité (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-72-transfert-entreprise-l1224-1', label: 'Transfert d’entreprise — L. 1224-1 (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-75-conges-payes-arret-maladie', label: 'Congés payés acquis pendant arrêt maladie (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-77-conge-paternite-maternite', label: 'Congé maternité / paternité — protection & indemnités (FR)', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-82-teletravail-accord', label: 'Télétravail — conformité et litige (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-84-conciliation-cph-bca', label: 'Conciliation CPH — BCO (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-86-appel-cph-cour-appel', label: 'Appel CPH cour d\'appel (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-87-pourvoi-cassation-soc', label: 'Pourvoi cassation sociale (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-88-execution-jugement-cph', label: 'Exécution jugement CPH / AGS (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-89-saisie-arret-remuneration', label: 'Saisie sur rémunération (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-90-action-groupe-discrimination', label: 'Action de groupe discrimination (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-91-faute-inexcusable-employeur', label: 'Faute inexcusable de l’employeur (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
];
