// Auto-généré depuis TOOL_REGISTRY (decisional-tools-panel.component.ts)
// + TOOL_LABEL static des composants — SF-158-02 F-158 landing V3.
// Refresh trimestriel : relancer build-catalog.py si TOOL_REGISTRY change.

export type LandingToolDomain = 'TRAVAIL' | 'IMMIGRATION' | 'FAMILLE';
export type LandingToolCountry = 'FR' | 'BE';
export type LandingToolType = 'CALCULATEUR' | 'SCORING' | 'COMPARATEUR' | 'GÉNÉRATEUR' | 'DÉTECTEUR' | 'OUTIL';

export interface LandingTool {
  id: string;
  label: string;
  domain: LandingToolDomain;
  country: LandingToolCountry;
  type: LandingToolType;
}

export const LANDING_TOOLS_CATALOG: LandingTool[] = [
  { id: 'F-DT-04-fiche-prudhomale', label: 'FICHE PRUD\'HOMALE', domain: 'TRAVAIL', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-DT-06-requete-tribunal-travail', label: 'REQUÊTE TRIBUNAL DU TRAVAIL', domain: 'TRAVAIL', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-DT-07-anciennete-conges-prime', label: 'ANCIENNETÉ ET CONGÉS', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-08-licenciement-validity', label: 'VALIDITÉ DU LICENCIEMENT', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-09-comparateur-indemnites', label: 'COMPARATEUR INDEMNITÉS', domain: 'TRAVAIL', country: 'FR', type: 'COMPARATEUR' },
  { id: 'F-DT-10-rupture-conv-validity', label: 'VALIDITÉ DE LA RUPTURE CONVENTIONNELLE', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-132-rupture-conv-indemnite', label: 'INDEMNITÉ RUPTURE CONVENTIONNELLE', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-11-harcelement-licenciement-nul', label: 'INDEMNITÉ LICENCIEMENT NUL — HARCÈLEMENT', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-16-licenciement-nul-detection', label: 'LICENCIEMENT NUL — DÉTECTION (ART. L.1235-3-1)', domain: 'TRAVAIL', country: 'FR', type: 'DÉTECTEUR' },
  { id: 'F-DT-12-discrimination-dommages-interets', label: 'DISCRIMINATION — DOMMAGES-INTÉRÊTS', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-13-licenciement-economique', label: 'LICENCIEMENT ÉCONOMIQUE (FR) — ART. L.1233-3/4/5/45', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-15-inaptitude', label: 'LICENCIEMENT POUR INAPTITUDE', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-19-heures-sup', label: 'RAPPEL HEURES SUPPLÉMENTAIRES', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-17-indemnite-precarite-cdd', label: 'INDEMNITÉ PRÉCARITÉ CDD', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-26-conges-payes-indemnite', label: 'INDEMNITÉ COMPENSATRICE DE CONGÉS PAYÉS', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-18-fin-mission-interim', label: 'INDEMNITÉ FIN MISSION INTÉRIM', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-32-documents-fin-contrat', label: 'DOCUMENTS DE FIN DE CONTRAT — CONFORMITÉ', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-34-refere-prudhomal', label: 'RÉFÉRÉ PRUD\'HOMAL R.1454-1 (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-21-travail-dissimule', label: 'INDEMNITÉ TRAVAIL DISSIMULÉ — L.8223-1', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-25-indemnite-preavis', label: 'INDEMNITÉ COMPENSATRICE DE PRÉAVIS', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-20-rappel-salaire', label: 'RAPPEL DE SALAIRE', domain: 'TRAVAIL', country: 'FR', type: 'CALCULATEUR' },
  { id: 'F-DT-22-requalification-cdd-cdi', label: 'REQUALIFICATION CDD → CDI (FR) — ART. L.1245', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-23-requalification-interim-cdi', label: 'REQUALIFICATION INTÉRIM → CDI (FR) — ART. L.1251-40', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-24-non-concurrence', label: 'CLAUSE DE NON-CONCURRENCE (FR) — CASS. SOC. 10/07/2002', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-132-rupture-amiable-info', label: 'RUPTURE AMIABLE', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-05-partage-immobilier', label: 'PARTAGE IMMOBILIER', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-15-recompenses', label: 'RÉCOMPENSES (ART. 1437/1469 CCIV)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-06-calendrier-garde', label: 'CALENDRIER DE GARDE', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-07-checklist-divorce', label: 'CHECKLIST DIVORCE', domain: 'FAMILLE', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-01-checklist-pieces', label: 'CHECKLIST PIÈCES IMMIGRATION', domain: 'IMMIGRATION', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-IM-05-arbre-decisionnel-titre', label: 'TITRE DE SÉJOUR RECOMMANDÉ', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-06-recours', label: 'RECOURS IMMIGRATION', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-07-droit-au-travail', label: 'DROIT AU TRAVAIL', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-oqtf-avec-delai-fr', label: 'OQTF AVEC DÉLAI DE DÉPART VOLONTAIRE (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-oqtf-sans-delai-fr', label: 'OQTF SANS DÉLAI DE DÉPART VOLONTAIRE (FR) — 48H', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-08-annexe13-be', label: 'ANNEXE 13 — OQT BELGE (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-08-referes-admin-fr', label: 'RÉFÉRÉS ADMINISTRATIFS L.521-1 / L.521-2 (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-35-contestation-are-fr', label: 'CONTESTATION ARE — FRANCE TRAVAIL (EX-PÔLE EMPLOI)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-27-motif-grave-be', label: 'MOTIF GRAVE BE (ART. 35 LOI 03/07/1978)', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-28-avantages-conventionnels-be', label: 'AVANTAGES CONVENTIONNELS BE', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-29-credit-temps-be', label: 'CRÉDIT-TEMPS / INTERRUPTION DE CARRIÈRE BE', domain: 'TRAVAIL', country: 'BE', type: 'OUTIL' },
  { id: 'F-DT-14-pse-validite', label: 'PSE — CRITÈRES DE VALIDITÉ (FR)', domain: 'TRAVAIL', country: 'FR', type: 'SCORING' },
  { id: 'F-DT-30-protection-rp', label: 'PROTECTION DES REPRÉSENTANTS DU PERSONNEL (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-33-at-mp', label: 'ACCIDENT DU TRAVAIL / MALADIE PROFESSIONNELLE (FR)', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-14-40ter-familial-belge-be', label: '40TER FAMILIAL BELGE (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-9bis-humanitaire-be', label: '9BIS HUMANITAIRE — RÉGULARISATION (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-9ter-medical-be', label: 'RÉGULARISATION 9TER MÉDICAL (BE)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-14-40bis-cohabitant-ue-be', label: 'REGROUPEMENT FAMILIAL — CITOYEN UE (ART. 40BIS)', domain: 'IMMIGRATION', country: 'BE', type: 'OUTIL' },
  { id: 'F-IM-09-aes-metiers-tension', label: 'AES MÉTIERS EN TENSION (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-famille', label: 'AES — VOIE FAMILIALE (L.435-1)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-08-divorce-alteration', label: 'DIVORCE — ALTÉRATION DÉFINITIVE LIEN CONJUGAL', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-09-divorce-faute', label: 'DIVORCE POUR FAUTE (FR) — ART. 242 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-10-divorce-accepte', label: 'DIVORCE ACCEPTÉ — ART. 233 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-12-mesures-provisoires', label: 'MESURES PROVISOIRES (FR) — ART. 254 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-13-revisions-post-divorce', label: 'RÉVISIONS POST-DIVORCE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-14-ordonnance-protection', label: 'ORDONNANCE DE PROTECTION (FR) — ART. 515-9 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-136-travail-procedure', label: 'CALENDRIER PROCÉDURAL — DROIT DU TRAVAIL', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-autorite-parentale', label: 'AUTORITÉ PARENTALE — EXERCICE (FR) — ART. 372-373 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-changement-residence', label: 'CHANGEMENT DE RÉSIDENCE (FR) — ART. 373-2 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-19-desaccords-parentaux', label: 'DÉSACCORDS PARENTAUX (FR) — ART. 373-2-10 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-22-indivision', label: 'INDIVISION POST-COMMUNAUTAIRE (ART. 815 CCIV)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-20-pacs-dissolution', label: 'DISSOLUTION PACS (FR) — ART. 515-7 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-25-majeurs-proteges', label: 'MAJEURS PROTÉGÉS (FR) — ART. 425-494 / 494-1 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-26-changement-etat-civil', label: 'CHANGEMENT D\'ÉTAT CIVIL (FR) — ART. 60 / 61-1 / 61-5 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-21-separation-corps', label: 'SÉPARATION DE CORPS + CONVERSION DIVORCE — ART. 296+306 CCIV', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-11-changement-statut', label: 'CHANGEMENT DE STATUT (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-13-naturalisation', label: 'NATURALISATION (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-19-mineurs', label: 'MINEURS ÉTRANGERS (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-20-mesures-eloignement', label: '20 MESURES ELOIGNEMENT', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-12-asile-avance', label: 'ASILE AVANCÉ (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-17-partage-judiciaire', label: 'PARTAGE JUDICIAIRE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-reconnaissance-paternelle', label: 'RECONNAISSANCE PATERNELLE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-contestation-paternite', label: 'CONTESTATION DE PATERNITÉ (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-recherche-paternite', label: 'RECHERCHE DE PATERNITÉ (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-possession-etat', label: 'POSSESSION D\'ÉTAT (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-18-adoption', label: 'ADOPTION (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-16-communaute-universelle', label: 'COMMUNAUTÉ UNIVERSELLE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-23-ordonnance-requete', label: 'ORDONNANCE SUR REQUÊTE (FR/BE)', domain: 'FAMILLE', country: 'FR', type: 'GÉNÉRATEUR' },
  { id: 'F-FA-24-devolution-legale', label: 'DÉVOLUTION LÉGALE SUCCESSORALE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-27-pma-gpa', label: 'PMA / GPA / BIOÉTHIQUE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-testament-validite', label: 'VALIDITÉ TESTAMENT (FR)', domain: 'FAMILLE', country: 'FR', type: 'SCORING' },
  { id: 'F-FA-24-donation', label: 'VALIDITÉ DONATION ENTRE VIFS (FR)', domain: 'FAMILLE', country: 'FR', type: 'SCORING' },
  { id: 'F-FA-24-reserve-heriditaire', label: 'RÉSERVE HÉRÉDITAIRE & ACTION EN RÉDUCTION (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-partage-successoral', label: 'PARTAGE SUCCESSORAL (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-indivision-successorale', label: 'INDIVISION SUCCESSORALE (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-24-rapport-succession', label: 'RAPPORT À SUCCESSION (FR)', domain: 'FAMILLE', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-17-regime-algerien', label: 'RÉGIME ALGÉRIEN (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-03-prescription-litige', label: 'DÉLAIS LÉGAUX', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-DT-31-transaction', label: 'TRANSACTION (FR) — ART. 2044 CCIV', domain: 'TRAVAIL', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-etudiant', label: 'AES VOIE ÉTUDIANTE (FR)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-IM-09-aes-humanitaire', label: 'AES — VOIE HUMANITAIRE (L.435-2)', domain: 'IMMIGRATION', country: 'FR', type: 'OUTIL' },
  { id: 'F-FA-11-desunion-irremediable-be', label: 'DIVORCE BE — DÉSUNION IRRÉMÉDIABLE (ART. 229 CC)', domain: 'FAMILLE', country: 'BE', type: 'OUTIL' },
];
