apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legalcase-ingress
spec:
  tls:
    - hosts:
        - legalcase.ng-itconsulting.com
      secretName: legalcase-tls-prod
  rules:
    - host: legalcase.ng-itconsulting.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: legalcase-frontend
                port:
                  number: 80
