apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: legalcase-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "55m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - staging.legalcase.ng-itconsulting.com
        - legalcase.ng-itconsulting.com
      secretName: legalcase-tls
  rules:
    - host: legalcase.ng-itconsulting.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: legalcase-frontend
                port:
                  number: 80
    - host: staging.legalcase.ng-itconsulting.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: legalcase-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: legalcase-frontend
                port:
                  number: 80
